##############################################################################
# GLVU GLUTILS MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME = glvuglutils
LIB_SRCS = glbuffers.cpp glutils.cpp textureobj.cpp glvutext.cpp gltextinput.cpp
PUBLIC_HEADERS= glbuffers.hpp glutils.hpp textureobj.hpp glvutext.hpp gltextinput.hpp

WITH_FEATURES := glut

include $(BASE_DIR)/Ubermake.defs
