##############################################################################
# TOP LEVEL GLVU UBER-MAKEFILE 
##############################################################################
BASE_DIR=.

TYPE=Tree

# Uncomment the things below that you want to build

TREE_DIRS := math math_objs camera glvu timer fileutils thread
#TREE_DIRS += images glutils 
#TREE_DIRS += object 
#TREE_DIRS += glvuext/libs
#TREE_DIRS += texdepthmesh lightcam envmapcube
#TREE_DIRS += examples


#=============================================================================
# In general, dirs should appear in dependency order.  So if 'foo'
# depends on 'bar' then 'bar' should be listed before 'foo'.


include $(BASE_DIR)/Ubermake.defs

#-----------------------------------------------------------------------------
# $Id: GNUmakefile,v 1.2 2002/07/04 02:33:32 baxter Exp $
#-----------------------------------------------------------------------------
