##############################################################################
# GLVU GLVU MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME=glvuglvu
glvuglvu_SRCS = glvu.cpp glvu_camview.cpp glvu_keyinput.cpp glvu_menu.cpp \
                glvu_mouse.cpp snapshot.cpp text.cpp trackball.c

PUBLIC_HEADERS= glvu.hpp text.hpp

WITH_FEATURES := glut

include $(BASE_DIR)/Ubermake.defs
