##############################################################################
# GLVU MATH MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME=glvumath
glvumath_SRCS = mat16fv.cpp mat44test.cpp vec3fv.cpp

PUBLIC_HEADERS= \
  mat16fv.hpp \
  mat33.hpp \
  mat33impl.hpp \
  mat44.hpp \
  mat44impl.hpp \
  vec2f.hpp \
  vec3f.hpp \
  vec3fv.hpp \
  vec4f.hpp \
  quat.hpp \
  quatimpl.hpp

include $(BASE_DIR)/Ubermake.defs
