##############################################################################
# GLVU TEXDEPTHMESH MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME = glvutdm
LIB_SRCS = texdepthmesh.cpp \
        texdepthmesh_disp_pts.cpp \
        texdepthmesh_disp_pts_float_step.cpp \
        texdepthmesh_disp_pts_int_step.cpp \
        texdepthmesh_disp_pts_adaptive.cpp \
        texdepthmesh_disp_pts_depthoffield.cpp \
        texdepthmesh_disp_mesh.cpp \
        texdepthmesh_disp_mesh_int_step.cpp \
        texdepthmeshset.cpp \
        texdepthmesh_hier.cpp \
        texdepthmesh_hier_node.cpp \
        texdepthmesh_hier_set.cpp


PUBLIC_HEADERS = texdepthmesh.hpp \
                 texdepthmesh_hier.hpp \
                 texdepthmesh_hier_node.hpp \
                 texdepthmesh_hier_set.hpp \
                 texdepthmeshset.hpp


WITH_FEATURES := glut

include $(BASE_DIR)/Ubermake.defs
