##############################################################################
# GLVU STOPWATCH MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME=glvutimer
LIB_SRCS = stopwatch.cpp
PUBLIC_HEADERS= stopwatch.hpp

include $(BASE_DIR)/Ubermake.defs
