##############################################################################
# GLVU MATH MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME=glvumathobjs
glvumathobjs_SRCS = minmaxbox.cpp plane.cpp tri.cpp

PUBLIC_HEADERS= \
  minmaxbox.hpp \
  plane.hpp \
  tri.hpp

include $(BASE_DIR)/Ubermake.defs
