##############################################################################
# GLVU LIGHTCAM MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME = glvulightcam
LIB_SRCS = lightcam.cpp lightcamprojector.cpp lightcamobj.cpp

PUBLIC_HEADERS = lightcam.hpp lightcamprojector.hpp lightcamobj.hpp

WITH_FEATURES := glut

include $(BASE_DIR)/Ubermake.defs


