##############################################################################
# GLVU ENVIRONMENT-MAPPED CUBE MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME = glvuemc
LIB_SRCS = envmapcube.cpp envmapcubeset.cpp
PUBLIC_HEADERS = envmapcube.hpp envmapcubeset.hpp

WITH_FEATURES := glut

include $(BASE_DIR)/Ubermake.defs
