##############################################################################
# GLVU FILEUTILS MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME = glvufileutils
LIB_SRCS = fileutils.cpp
PUBLIC_HEADERS= fileutils.hpp

include $(BASE_DIR)/Ubermake.defs
