##############################################################################
# GLVU CAMERA MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME=glvucamera
glvucamera_SRCS = camdisplay.cpp camera.cpp camutils.cpp

PUBLIC_HEADERS= camera.hpp camutils.hpp

WITH_FEATURES := glut

include $(BASE_DIR)/Ubermake.defs
