##############################################################################
# GLVU IMAGES MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME=glvuimages
VPATH := pgm ppm rgb tga
LIB_SRCS = pgm.cpp ppm.cpp rgb.cpp tga.cpp
PUBLIC_HEADERS= ppm.hpp pgm.hpp rgb.hpp tga.hpp

include $(BASE_DIR)/Ubermake.defs
