##############################################################################
# GLVUEXT LIB THREAD MAKEFILE
##############################################################################
BASE_DIR=..
TYPE = Lib
LIB_NAME = glvuthread
LIB_SRCS = thread.cpp threadutil.cpp

PUBLIC_HEADERS = thread.hpp

# use 'WITH_FEATURES = threads' when linking with this library

include $(BASE_DIR)/Ubermake.defs
